  Pruebas_Frontend:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
      - run: echo "Probando frontend..." && sleep 5

  Pruebas_Backend:
    needs: Compilacion
    runs-on: ubuntu-latest
    steps:
      - run: echo "Probando backend..." && sleep 5
